owner: ononoki1
repo: status

sites:
  - name: DNS
    check: tcp-ping
    url: 107.172.8.80
    port: 53
  - name: Homepage
    url: https://ononoki.org/
    expectedStatusCodes:
      - 200
  - name: Search
    url: https://search.ononoki.org/
    expectedStatusCodes:
      - 200
  - name: Morty
    url: https://morty.ononoki.org/
    expectedStatusCodes:
      - 200
  - name: Blog
    url: https://blog.ononoki.org/
    expectedStatusCodes:
      - 200
  - name: Comment
    url: https://comment.ononoki.org/
    expectedStatusCodes:
      - 200
  - name: Drive
    url: https://drive.ononoki.org/
    expectedStatusCodes:
      - 200
  - name: Font
    url: https://font.ononoki.org/font.css
    expectedStatusCodes:
      - 200
  - name: Paste
    url: https://paste.ononoki.org/
    expectedStatusCodes:
      - 200
  - name: '2048'
    url: https://2048.ononoki.org/
    expectedStatusCodes:
      - 200
  - name: IP
    url: https://ip.ononoki.org/
    expectedStatusCodes:
      - 200

status-website:
  cname: status.ononoki.org
  logoUrl: https://ononoki.org/images/ononoki.jpg
  name: ononoki's Status
  introTitle: ononoki's Status
  navbar:
    - title: Status
      href: /
    - title: Homepage
      href: https://ononoki.org/
  customHeadHtml: <script>var _paq=window._paq=window._paq||[];_paq.push(["setDocumentTitle",document.domain+"/"+document.title]);_paq.push(["setCookieDomain","*.ononoki.org"]);_paq.push(["setDomains","*.ononoki.org"]);_paq.push(['trackPageView']);_paq.push(['trackAllContentImpressions']);_paq.push(['enableLinkTracking']);_paq.push(['enableHeartBeatTimer',1]);(function(){var u="https://ononoki.org/m/";_paq.push(['setTrackerUrl',u+'m.php']);_paq.push(['setSiteId','8']);var d=document,g=d.createElement('script'),s=d.getElementsByTagName('script')[0];g.async=true;g.src=u+'m.js';s.parentNode.insertBefore(g,s);})();</script><noscript><p><img src="https://ononoki.org/m/m.php?idsite=8&amp;rec=1" style="border:0;" alt="" /></p></noscript>

i18n:
  footer: Powered by <a href='https://ononoki.org/' rel='noopener' target='_blank'><strong>ononoki</strong></a>.

skipDescriptionUpdate: true
skipTopicsUpdate: true
skipHomepageUpdate: true
