owner: ononoki1
repo: status
sites:
  - name: Authoritative name server
    check: tcp-ping
    url: 192.3.81.160
    port: 53
  - name: Homepage
    url: https://ononoki.org
    expectedStatusCodes:
      - 200
  - name: 2048 game
    url: https://2048.ononoki.org
    expectedStatusCodes:
      - 200
  - name: Blog
    url: https://blog.ononoki.org
    expectedStatusCodes:
      - 200
  - name: Comment
    url: https://comment.ononoki.org
    expectedStatusCodes:
      - 200
  - name: Drive
    url: https://drive.ononoki.org
    expectedStatusCodes:
      - 200
  - name: Index
    url: https://index.ononoki.org
    expectedStatusCodes:
      - 200
  - name: IP query
    url: https://ip.ononoki.org
    expectedStatusCodes:
      - 200
  - name: MortyProxy
    url: https://morty.ononoki.org
    expectedStatusCodes:
      - 200
  - name: Pastebin
    url: https://paste.ononoki.org
    expectedStatusCodes:
      - 200
  - name: Search
    url: https://search.ononoki.org
    expectedStatusCodes:
      - 200
  - name: Tor exit node
    check: tcp-ping
    url: 107.189.30.115
    port: 443
status-website:
  cname: status.ononoki.org
  logoUrl: https://ononoki.org/images/ononoki.jpg
  name: ononoki's Status
  introTitle: ononoki's Status
  navbar:
    - title: Status
      href: /
    - title: Homepage
      href: https://ononoki.org
  customHeadHtml: <script src="//ononoki.org/js/m.js"></script><noscript><p><img src="//ononoki.org/m/m.php?idsite=8&amp;rec=1" style="border:0;" alt="" /></p></noscript>
i18n:
  footer: Powered by <a href="//ononoki.org" target="_blank"><strong>ononoki</strong></a>.
skipDescriptionUpdate: true
skipTopicsUpdate: true
skipHomepageUpdate: true
